stages:
  - test_image
  - test

test_image:
  image: docker:git
  services:
  - name: docker:dind
    entrypoint: ["dockerd-entrypoint.sh"]
    command: ["--insecure-registry", "172.17.0.1:5000"]
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd test && docker build -t $CI_REGISTRY/karl/pbuf:latest .
    - docker push $CI_REGISTRY/karl/pbuf:latest
  only:
    - master

test:
  image: $CI_REGISTRY/karl/pbuf:latest

  before_script:
    - MIX_ENV=test mix deps.get

  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - deps/
      - _build/

  script:
    - make gen
    - make t
