image: elixir:1.8.1-slim

before_script:
  - apt-get update && apt-get -y install wget unzip build-essential
  - wget -q https://github.com/protocolbuffers/protobuf/releases/download/v3.7.0rc1/protoc-3.7.0-rc1-linux-x86_64.zip
  - unzip protoc-3.7.0-rc1-linux-x86_64.zip
  - mv bin/protoc /usr/local/bin
  - mv include/google/ /usr/local/include/google/
  - mix local.hex --force
  - MIX_ENV=test mix deps.get
  - export PATH=~/.mix/escripts/:$PATH
  - yes | mix escript.install hex protobuf || true

test:
  script:
  - make gen
  - make t
